# Generated by Django 2.2.10 on 2022-04-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdcuForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='mainretention',
            name='product_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_form_id', to='planner.ProdcuForm'),
        ),
    ]
