# Generated by Django 2.2.10 on 2022-04-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20220412_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainretention',
            name='season',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
