# Generated by Django 2.2.10 on 2022-04-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20220412_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeshare',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='upctransferencesummary',
            name='retention',
        ),
    ]
