# Generated by Django 2.2.10 on 2022-04-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20220413_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributefilter',
            name='brand',
        ),
    ]
