# Generated by Django 2.2.10 on 2022-04-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_remove_attributefilter_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdcuForm',
            new_name='ProdcutForm',
        ),
    ]
