# Generated by Django 2.2.10 on 2022-04-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20220418_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdcutForm',
            new_name='ProductForm',
        ),
    ]
