# Generated by Django 2.2.10 on 2022-04-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20220420_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomment',
            name='parent_comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='planner.Comments'),
        ),
    ]
