# Generated by Django 2.2.10 on 2022-04-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20220420_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='parent_comment_id',
        ),
        migrations.AddField(
            model_name='subcomment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment_id', to='planner.Comments'),
        ),
    ]
