# Generated by Django 2.2.10 on 2022-04-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_auto_20220420_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
